### ISSUE TITLE
'dtaidistance\dtw_cc.pyx' doesn't match any files

### ISSUE THREAD

**Issue by Huii** [wannesm/dtaidistance#88]
Whenever I attempt to install dtaidistance on Windows 10 from another Folder than the main root folder, I'm greated with the following error message:

`ValueError: 'dtaidistance\dtw_cc.pyx' doesn't match any files`

This issue seems to be related to [this issue](https://github.com/wannesm/dtaidistance/issues/76) and does **not** occur if I decide to build everything from source from within the root folder. I guess this is just a remaining path Problem somewhere in setup.py and probably affects only Windows machines.

**Comment by wannesm** [comment]
I figured out that Cython uses the glob package for finding files, and thus unix-style paths. I changed the paths to be compatible with Cython. Maybe this resolves it for Windows.

**Comment by Huii** [comment]
Unfortunately, that didn't change anything on my machine. Handling paths seems to be a real pain on Windows. :(

**Comment by wannesm** [comment]
The latest version should fix this and it now compiles on Windows. I tested it on Windows 10 using Microsoft Visual C (MSVC).

**Comment by Huii** [comment]
I'm very sorry but it still doesn't work from another directory on my Windows 10 machine. I still have to be in the root directory if I want to start the compilation.

**Comment by wannesm** [comment]
Good to hear it works from the root directory.

Can you remind me of the use case for running it from another directory? Does this work for other Cython projects?

**Comment by Huii** [comment]
I don't know about other Cython projects as this is the only one I use. Also, there is no real crucial use case for this feature. It would just be nice to avoid confusion for first-time users. However, I think it should also be ok to just leave this as it is for now (if there is no way to fix it) and mention in the documentation that on Windows, you have to install it from the root folder.
