### ISSUE TITLE
import issues

### ISSUE THREAD

**Issue by csalinasonline** [wannesm/dtaidistance#91]
Installed via pip
> pip install dtaidistance

Tried importing into script
> from dtaidistance import clustering

But get error
> ImportError: cannot import name 'clustering' from 'dtaidistance' (/home/xnorsis/.conda/envs/P000001/lib/python3.7/site-packages/dtaidistance/__init__.py)

Please advise?

**Comment by wannesm** [comment]
Which version of dtaidistance have you installed? The clustering package is a recent addition so you might need to run `pip install --upgrade dtaidistance`.

**Comment by ahitboyZBW** [comment]
I tried to upgrade, but the error still exists?

pip install --upgrade dtaidistance
Requirement already up-to-date: dtaidistance in ****/opt/anaconda3/lib/python3.8/site-packages (2.1.0)
Requirement already satisfied, skipping upgrade: cython in /Users/bowen/opt/anaconda3/lib/python3.8/site-packages (from dtaidistance) (0.29.21)

from dtaidistance import clustering
---------------------------------------------------------------------------
ImportError: cannot import name 'clustering' from 'dtaidistance' (/Users/bowen/opt/anaconda3/lib/python3.8/site-packages/dtaidistance/__init__.py)

**Comment by wannesm** [comment]
You're correct. The setup file was not covering the clustering submodule. Should be fixed now.

**Comment by csalinasonline** [comment]
I just updated to 2.2.1 but still get error importing clustering?
